debug: false

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 20000
      org.quartz.scheduler.instanceName: my-clustered-scheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.interruptJobsOnShutdown: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true&allowMultiQueries=true
    username: ENC(riUZAgnTJHneKLxEyEEVXA==)
    password: ENC(Lhnswc4SYky2bn+joCPGxQ==)

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: securityKey

